dist: bionic
language: python

python:
  - '3.7'

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable

branches:
  only:
    - collection_pop_production
    
install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  # ajouter tchappui-webdrivers dans requirements.txt
  - install-webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="collection_pop.settings.travis"

services:
  - postgresql

script:
  - python manage.py test -v2