# Generated by Django 3.0.7 on 2020-06-30 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('figurines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Did_you_see',
            new_name='DidYouSee',
        ),
        migrations.RenameField(
            model_name='figurine',
            old_name='id_category',
            new_name='category',
        ),
    ]
