# Generated by Django 3.0.8 on 2020-07-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figurines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didyousee',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='figurines.DidYouSee'),
        ),
    ]
