# Generated by Django 3.0.8 on 2020-08-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figurines', '0002_auto_20200715_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='didyousee',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
