# Generated by Django 3.0.7 on 2020-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figurines', '0002_auto_20200630_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurine',
            name='picture_figurine',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
