# Generated by Django 3.0.8 on 2020-07-02 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('figurines', '0004_auto_20200702_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='didyousee',
            name='author',
        ),
        migrations.AddField(
            model_name='didyousee',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
