# Generated by Django 3.0.8 on 2020-07-03 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('figurines', '0005_auto_20200702_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='didyousee',
            name='author',
        ),
        migrations.AddField(
            model_name='didyousee',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
