# Generated by Django 3.0.8 on 2020-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figurines', '0006_auto_20200703_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='didyousee',
            options={'ordering': ['datetime'], 'verbose_name': 'article'},
        ),
        migrations.AddField(
            model_name='didyousee',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
