# Generated by Django 3.0.8 on 2020-07-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figurines', '0007_auto_20200703_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='didyousee',
            options={'ordering': ['-datetime'], 'verbose_name': 'article'},
        ),
    ]
