# Generated by Django 3.0.8 on 2020-07-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figurines', '0008_auto_20200703_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didyousee',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date de parution'),
        ),
    ]
